"""Current-year orchestration: project indicators, then Denton, then spatially reconcile."""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd

from .denton import BenchmarkMetadata, proportional_denton
from .indicator_projection import project_missing_quarters
from .spatial import reconcile_spatial


def run_current_year_pipeline(
    observed_indicator_rows: pd.DataFrame,
    annual_benchmark: BenchmarkMetadata,
    spatial_weights: pd.DataFrame,
    *,
    current_quarter: int,
    projected_indicator_rows: pd.DataFrame | None = None,
    projection_method: str = "explicit",
    as_of_date: str | date | None = None,
    output_root: Path | None = None,
) -> dict[str, pd.DataFrame]:
    """Complete the current-year indicators, then run Denton and spatial steps.

    No future indicator is generated by Denton. With the default ``explicit``
    method, all missing future quarters must be supplied by the caller.
    """
    target_year = int(annual_benchmark.benchmark_year)
    complete = project_missing_quarters(
        observed_indicator_rows,
        target_year,
        current_quarter,
        projected_indicator_rows=projected_indicator_rows,
        method=projection_method,  # type: ignore[arg-type]
        as_of_date=as_of_date,
    )
    denton = proportional_denton(
        complete,
        {target_year: annual_benchmark},
    )
    province = reconcile_spatial(denton, spatial_weights)
    if output_root is not None:
        output_root.mkdir(parents=True, exist_ok=True)
        complete.to_csv(output_root / "raw_xgb_quarterly_indicators.csv", index=False)
        denton.to_csv(output_root / "denton_quarterly_estimates.csv", index=False)
        province.to_csv(output_root / "province_quarterly_estimates.csv", index=False)
    return {"raw": complete, "denton": denton, "province": province}
